### PR TITLE
IGNITE-19068 Sql. Support sql engine representation for kv api timestamp type

### PR DESCRIPTION
**Pull request by zstan**

### CODE REVIEW

**Comment by zstan** [comment]
@korlov42 can u make a review plz ?

**Comment by zstan** [comment]
@AMashenkov can you make a review plz ?

**Review by korlov42 — CHANGES_REQUESTED** [review]
The patch looks good, but, apart tests on interoperation, it worth to add tests to verify behaviour of the type itself (see org.apache.ignite.internal.sql.engine.ItDataTypesTest)

**Comment by zstan** [comment]
@korlov42  i append additional integration sqllogic tests, as i understand soon they become unmuted and thus it`s appropriate change, isn`t it ?

**Review by AMashenkov — APPROVED** [review]

**Pull request closed without merging**
