### PR TITLE
IGNITE-18369: SQL. Incorrect inferred return type for functions for NUMERIC types

### PR DESCRIPTION
**Pull request by lowka**

### CODE REVIEW

**Review by AMashenkov — APPROVED** [review]
Please fix conflicts.

**Comment by zstan** [comment]
but standard is : 
image

**Comment by zstan** [comment]
COALESCE (V1, V2) is equivalent to the following <case specification>:
CASE WHEN V1
IS NOT NULL THEN
V1 ELSE
V2 END

**Comment by lowka** [comment]
@zstan 

> COALESCE (V1, V2) is equivalent to the following :
> CASE WHEN V1
> IS NOT NULL THEN
> V1 ELSE
> V2 END
Well sure it is but could you please elaborate? Do we need some additional test cases or what?

**Comment by zstan** [comment]
I think this mean that this test need to be passed, wdyt ? 
assertQuery("SELECT COALESCE(?, ?)").withParams("a", 10).returns("a").check();

**Comment by lowka** [comment]
> assertQuery("SELECT COALESCE(?, ?)").withParams("a", 10).returns("a").check();

This test case should fail b/c we do int -> varchar coercion was explicitly disabled.

**Pull request merged**
